### ISSUE TITLE
Not working with russian letters. 

### ISSUE THREAD

**Issue by stepan-chircioglo** [2amigos/yii2-transliterator-helper#2]
Осень в мае -> osenʹ v mae
Осенъ в мае -> osenʺ v mae

on test server not working.
php version 5.4.4 intl enabled

but in my local machine working.
difference
php 5.5.9

what the problem?

letters 'ь'  and 'ъ' -> must be removed

**Comment by Sirgalas** [comment]
If assistance more urgent, I can. But just in the russian language there is not a sign ' so that everything you do with this sign space.

**Comment by alexantr** [comment]
Instead `Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC;` use `Any-Latin; Latin-ASCII; [\u0100-\u7fff] remove`

**Comment by tonydspaniard** [comment]
@alexantr have time for a PR?

**Comment by alexantr** [comment]
@tonydspaniard, I checked transliteration with `Any-Latin; Latin-ASCII; [\u0100-\u7fff] remove`. With this variant `ь` and `ъ` converts to ASCII symbols `'` and `"` instead non-ASCII `ʹ` and `ʺ`. @stepan-chircioglo still must remove `'` and `"` manually.

**Comment by tonydspaniard** [comment]
@alexantr any help with a russian PR would be highly appreciated. I do not speak the language.

**Comment by alexantr** [comment]
Check #3

**Comment by tonydspaniard** [comment]
@Sirgalas @stepan-chircioglo please test on `master`, if all work as expected, I'll tag new version.

**Comment by tonydspaniard** [comment]
This should have been fixed by https://github.com/2amigos/yii2-transliterator-helper/pull/3
